"""initial schema

Revision ID: 9d59342bbe75
Revises: 
Create Date: 2026-10-02 01:41:07.733699
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '9d59342bbe75'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('audience', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.Column('action', sa.String(length=500), nullable=False),
    sa.Column('deadline', sa.String(length=255), nullable=False),
    sa.Column('contact_path', sa.String(length=500), nullable=False),
    sa.Column('tone', sa.String(length=255), nullable=False),
    sa.Column('locale', sa.String(length=35), nullable=False),
    sa.Column('risk_level', sa.Enum('ROUTINE', 'MODERATE', 'HIGH', name='risklevel', native_enum=False, length=16), nullable=False),
    sa.Column('source_message', sa.Text(), nullable=False),
    sa.Column('revised_message', sa.Text(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('open_questions', sa.JSON(), nullable=False),
    sa.Column('reading_level', sa.JSON(), nullable=True),
    sa.Column('state', sa.Enum('DRAFT', 'REVISED', 'APPROVED', 'TRANSLATED', 'VERIFIED', 'ESCALATED', name='messagestate', native_enum=False, length=16), nullable=False),
    sa.Column('approved_message', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('reviewer_feedback', sa.Text(), nullable=True),
    sa.Column('target_languages', sa.JSON(), nullable=False),
    sa.Column('pii_warnings', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_state'), ['state'], unique=False)

    op.create_table('protected_items',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.String(length=24), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('placeholder', sa.String(length=16), nullable=False),
    sa.Column('must_match_exactly', sa.Boolean(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('context_sentence', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('protected_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_protected_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_protected_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_protected_items_item_type'), ['item_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_protected_items_message_id'), ['message_id'], unique=False)

    op.create_table('translations',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('target_language', sa.String(length=12), nullable=False),
    sa.Column('locale', sa.String(length=35), nullable=True),
    sa.Column('translated_message', sa.Text(), nullable=False),
    sa.Column('back_translation', sa.Text(), nullable=True),
    sa.Column('back_translation_similarity', sa.Float(), nullable=True),
    sa.Column('placeholders', sa.JSON(), nullable=False),
    sa.Column('protected_items', sa.JSON(), nullable=False),
    sa.Column('uncertainties', sa.JSON(), nullable=False),
    sa.Column('terminology_notes', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_translations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_translations_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_translations_target_language'), ['target_language'], unique=False)

    op.create_table('verification_reports',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('translation_id', sa.String(length=36), nullable=False),
    sa.Column('target_language', sa.String(length=12), nullable=False),
    sa.Column('overall_status', sa.String(length=24), nullable=False),
    sa.Column('human_review_required', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('risk_evidence', sa.JSON(), nullable=False),
    sa.Column('risk_declared_by_user', sa.String(length=16), nullable=True),
    sa.Column('escalation_note', sa.Text(), nullable=True),
    sa.Column('review_requirements', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['translation_id'], ['translations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_reports_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_reports_overall_status'), ['overall_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_reports_translation_id'), ['translation_id'], unique=False)

    op.create_table('back_translation_pairs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('source_sentence', sa.Text(), nullable=False),
    sa.Column('back_translated', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['verification_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('back_translation_pairs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_back_translation_pairs_report_id'), ['report_id'], unique=False)

    op.create_table('fact_checks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('source_value', sa.Text(), nullable=False),
    sa.Column('translated_value', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['verification_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fact_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_checks_report_id'), ['report_id'], unique=False)

    op.create_table('tone_assessments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('tone', sa.String(length=32), nullable=False),
    sa.Column('mechanical_phrases', sa.JSON(), nullable=False),
    sa.Column('cultural_awkwardness', sa.JSON(), nullable=False),
    sa.Column('terminology_notes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['verification_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_table('verification_issues',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['verification_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_issues_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_issues_report_id'))

    op.drop_table('verification_issues')
    op.drop_table('tone_assessments')
    with op.batch_alter_table('fact_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_checks_report_id'))

    op.drop_table('fact_checks')
    with op.batch_alter_table('back_translation_pairs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_back_translation_pairs_report_id'))

    op.drop_table('back_translation_pairs')
    with op.batch_alter_table('verification_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_reports_translation_id'))
        batch_op.drop_index(batch_op.f('ix_verification_reports_overall_status'))
        batch_op.drop_index(batch_op.f('ix_verification_reports_message_id'))
        batch_op.drop_index(batch_op.f('ix_verification_reports_id'))
        batch_op.drop_index(batch_op.f('ix_verification_reports_created_at'))

    op.drop_table('verification_reports')
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translations_target_language'))
        batch_op.drop_index(batch_op.f('ix_translations_message_id'))
        batch_op.drop_index(batch_op.f('ix_translations_id'))
        batch_op.drop_index(batch_op.f('ix_translations_created_at'))

    op.drop_table('translations')
    with op.batch_alter_table('protected_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_protected_items_message_id'))
        batch_op.drop_index(batch_op.f('ix_protected_items_item_type'))
        batch_op.drop_index(batch_op.f('ix_protected_items_id'))
        batch_op.drop_index(batch_op.f('ix_protected_items_created_at'))

    op.drop_table('protected_items')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_state'))
        batch_op.drop_index(batch_op.f('ix_messages_risk_level'))
        batch_op.drop_index(batch_op.f('ix_messages_id'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))

    op.drop_table('messages')
    # ### end Alembic commands ###
